///* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
///* Header for class ThreeBRunner */
//
//#ifndef _Included_ThreeBRunner
//#define _Included_ThreeBRunner
//#ifdef __cplusplus
//extern "C" {
//#endif
///*
// * Class:     ThreeBRunner
// * Method:    call
// * Signature: (Ljava/lang/String;[[F[BIIILjava/lang/String;)V
// */
//JNIEXPORT void JNICALL Java_ThreeBRunner_call
//  (JNIEnv *, jobject, jstring, jobjectArray, jbyteArray, jint, jint, jint, jstring);
//
//#ifdef __cplusplus
//}
//#endif
//#endif
